<#
Exposed parameters for creating the Processing Role, so you can change it for production
#>
$Prefix = "xp901" #This is usually the name of the site
$PSScriptRoot = "c:\xp" #This is the default destination folder from the git clone, if different then update this to point to the new location.
$Path = "$PSScriptRoot\config\sitecore-XP1-prc.json"

$Package = "$PSScriptRoot\Sitecore 9.0.1 rev. 171219 (OnPrem)_prc.scwdp.zip"
$LicenseFile = "$PSScriptRoot\license.xml" #The Sitecore License.xml file
$SiteName = "$Prefix.processing" #The website that will be created in IIS

$SSLCert = "" #Todo: needs to be provided (applicable for production environment), if not then generated by the script (applicable for development environment).
$XConnectCert = "$Prefix.xconnect_client" 

<#
The $Prefix, $SqlAdminUser, $SqlAdminPassword and $SqlServer needs to be changes. The rest can use the default values (for development environment purposes) but for production it's recommended to be changed.
#>
$SqlDbPrefix = $Prefix
$SqlServer = "RAMONASENIE0E1F"
$SqlAdminUser = "sa" 
$SqlAdminPassword="jajnav5@" 
$SqlCoreUser = "coreuser"
$SqlCorePassword = "Test12345"
$SqlMasterUser = "masteruser"
$SqlMasterPassword = "Test12345"
$SqlWebUser = "webuser"
$SqlWebPassword = "Test12345"
$SqlReportingUser = "reportinguser"
$SqlReportingPassword = "Test12345"
$SqlReferenceDataUser = "referencedatauser"
$SqlReferenceDataPassword = "Test12345"
$SqlProcessingPoolsUser = "poolsuser"
$SqlProcessingPoolsPassword = "Test12345"
$SqlProcessingTasksUser = "tasksuser"
$SqlProcessingTasksPassword = "Test12345"

$SolrCorePrefix = $Prefix
$SolrUrl = "https://localhost:8983/solr" 

$XConnectCollectionService = "https://$Prefix.xconnectcollection"
$ReportingServiceApiKey = "abcde111112222233333444445555566"

#Configure Processing role
$ProcessingParams = @{     
    Path = $Path
    Package = $Package     
    LicenseFile = "$PSScriptRoot\license.xml"   
    XConnectCert = $XConnectCert  
    SSLCert = $SSLCert
    SqlDbPrefix = $Prefix
    SolrCorePrefix = $SolrCorePrefix
    SiteName = $SiteName
    SqlAdminUser = $SqlAdminUser
    SqlAdminPassword = $SqlAdminPassword
    SqlCoreUser = $SqlCoreUser
    SqlCorePassword = $SqlCorePassword
    SqlMasterUser = $SqlMasterUser
    SqlMasterPassword = $SqlMasterPassword
    SqlWebUser = $SqlWebUser
    SqlWebPassword = $SqlWebPassword
    SqlReportingUser = $SqlReportingUser
    SqlReportingPassword = $SqlReportingPassword
    SqlReferenceDataUser = $SqlReferenceDataUser
    SqlReferenceDataPassword = $SqlReferenceDataPassword
    SqlProcessingPoolsUser = $SqlProcessingPoolsUser
    SqlProcessingPoolsPassword = $SqlProcessingPoolsPassword
    SqlProcessingTasksUser = $SqlProcessingTasksUser
    SqlProcessingTasksPassword = $SqlProcessingTasksPassword
    SqlServer = $SqlServer
    SolrUrl = $SolrUrl
    XConnectCollectionService  = $XConnectCollectionService
    ReportingServiceApiKey = $ReportingServiceApiKey
} 
Write-Host @ProcessingParams
Install-SitecoreConfiguration @ProcessingParams -Verbose

<#
MIT License

Copyright (c) 2018 Ramon Aseniero

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#>